#!/bin/bash
set -e
CMD_LINE_FILE=/etc/efigen/cmdline.txt
OS_RELEASE_FILE=/usr/lib/os-release
KERNEL=/boot/vmlinuz-linux
INITRDS=/boot/initramfs-linux.img
TEMP_INITRD_IMG=./temp.img
source /etc/efigen/efigen.config
cat $INITRDS > $TEMP_INITRD_IMG
objcopy \
    --add-section .osrel="$OS_RELEASE_FILE" --change-section-vma .osrel=0x20000 \
    --add-section .cmdline="$CMD_LINE_FILE" --change-section-vma .cmdline=0x30000 \
    --add-section .linux="$KERNEL" --change-section-vma .linux=0x40000 \
    --add-section .initrd="$TEMP_INITRD_IMG" --change-section-vma .initrd=0x3000000 \
    "/usr/lib/systemd/boot/efi/linuxx64.efi.stub" "/boot/linux.efi"
rm $TEMP_INITRD_IMG
